site_name: ibm-cloud-apac-training
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette:
    scheme: default
    primary: black
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  language: en
